#----------------------------------------------------------------------------
#       Make Workspace
#
# 
#
# This file was generated by MPC.  Any changes made directly to
# this file will be lost the next time it is generated.
#
# MPC Command:
# /home/chajmart/MPC/mwc.pl -type make
#
#----------------------------------------------------------------------------


all: banker

depend: banker-depend

clean generated realclean check-syntax $(CUSTOM_TARGETS):
	@$(MAKE) -f Makefile.banker $(@)

.PHONY: banker
banker:
	@$(MAKE) -f Makefile.banker all

.PHONY: banker-depend
banker-depend:
	@$(MAKE) -f Makefile.banker depend

project_name_list:
	@echo banker

run:
	./a.out 10 5 7
